name: CI - Build and Test

on:
  push:
    branches: [main, develop,Allowance]
  pull_request:
    branches: [main, develop,Allowance]

jobs:
  # ========================
  # BACKEND - SPRING BOOT
  # ========================
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('BE/pom.xml') }}
          restore-keys: | 
            ${{ runner.os }}-m2-
      - name: Run Backend Tests
        working-directory: BE
        run: mvn test

      - name: Build Backend
        working-directory: BE
        run: mvn -B clean package

    
